### ISSUE TITLE
Change the derivation path for wallet

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-ledger#34]
The current implementation is using BIP44 for keychain derivation path, but this one is not efficient for the archethic keychain use case, as the implementations on clients.
So we are introducing a new derivation path for keychain `﻿﻿﻿﻿m/650'/account'/index'` where account can be anything and customized for each keychain and where index is the number of transaction in the chain. 

The implementation of the derivation key is then custom.

About the implementation, because the hardware limitations must be considered, we might not use child derivation key function like in BIP32 (recursive and cumulative) but one-time operation to generate the private key. 

For example: HMAC-512(Key=seed, Data=SHA256(derivationPath)), where the first 256 bytes of the digest are the private key.

The wallet spec is updated: https://archethic-foundation.github.io/archethic-docs/build/clients/wallet-spec)

Javascript client PR implements this new change: archethic-foundation/libjs#37

📝📝 Actions List

- [X] Change Derivation Path for DeriveKeyPair
- [X] Modify for Ledger Origin PublicKey
- [X] Modify the Wallet Encoder with new Encoding scheme
- [X] Modify for new Encoded Wallet in `generateKeyFromWallet` fn
- [X] Change Decoding of wallet as per new encoding
- [X] Derive Address as per new Scheme
- [X] Modify txn signature for new path
- [X] Modify tests
- [X] Test Changes with H/W Device
- [X] Sanitize Code from Debug Flags

**Comment by prix-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-ledger/34?planning-poker) with ZenHub @samuel-uniris @internet-zero
